# Feature Engineering

### 1. Merge All Relevant Data

In [2]:
import pandas as pd
import os

In [3]:
print("Current working directory:", os.getcwd())

Current working directory: C:\Users\Harpreet\Desktop\EduPro_Project\notebooks

In [4]:
users = pd.read_csv("/Users/harpreet/Desktop/EduPro_Project/data/EduPro Online Platform.xlsx - Users.csv")
courses = pd.read_csv("/Users/harpreet/Desktop/EduPro_Project/data/EduPro Online Platform.xlsx - Courses.csv")
transactions = pd.read_csv("/Users/harpreet/Desktop/EduPro_Project/data/EduPro Online Platform.xlsx - Transactions.csv")
teachers = pd.read_csv("/Users/harpreet/Desktop/EduPro_Project/data/EduPro Online Platform.xlsx - Teachers.csv")

In [5]:
users

      UserID        UserName  Age  Gender                             Email
0     U00001    wilsonjordan   15    Male            patricia27@hotmail.com
1     U00002        angela22   29  Female             hallrandy@hotmail.com
2     U00003  morrisonamanda   33  Female               ganderson@yahoo.com
3     U00004       fthornton   23  Female  christensencatherine@outlook.com
4     U00005  fostergeoffrey   21    Male            karenfuentes@yahoo.com
...      ...             ...  ...     ...                               ...
2995  U02996    rebeccamccoy   32    Male               james28@outlook.com
2996  U02997          jburke   21  Female                  nramos@yahoo.com
2997  U02998      choikendra   33    Male         katherinebeck@hotmail.com
2998  U02999    rachelmalone   20    Male          rodgerserica@hotmail.com
2999  U03000   harperdouglas   15    Male                jackie41@gmail.com

[3000 rows x 5 columns]

In [6]:
courses

,CourseID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,CR00001,Python Basics,Programming,Paid,Beginner,472.28,11.00,4.74
1,CR00002,Java Programming,Programming,Free,Intermediate,0.00,37.70,2.43
2,CR00003,C++ for Beginners,Programming,Free,Beginner,0.00,19.53,3.85
3,CR00004,Advanced Python,Programming,Free,Beginner,0.00,45.13,2.88
4,CR00005,Full Stack Development,Programming,Free,Beginner,0.00,28.68,1.28
5,CR00006,Graphic Design Basics,Design,Paid,Advanced,276.37,48.84,2.72
6,CR00007,UI/UX Design,Design,Free,Advanced,0.00,48.68,2.61
7,CR00008,Photoshop Mastery,Design,Free,Advanced,0.00,2.87,1.52
8,CR00009,Web Design Fundamentals,Design,Free,Beginner,0.00,48.19,4.51
9,CR00010,3D Modeling,Design,Free,Advanced,0.00,15.29,4.45
10,CR00011,Entrepreneurship 101,Business,Paid,Intermediate,326.02,11.31,2.69
11,CR00012,Business Strategy,Business,Paid,Advanced,487.92,36.01,3.64
12,CR00013,Finance for Startups,Business,Free,Advanced,0.00,15.84,2.00
13,CR00014,Sales Mastery,Business,Free,Advanced,0.00,22.29,3.15
14,CR00015,Leadership Essentials,Business,Paid,Beginner,285.05,34.78,1.96
15,CR00016,Digital Marketing,Marketing,Free,Intermediate,0.00,42.68,4.72
16,CR00017,SEO Mastery,Marketing,Free,Advanced,0.00,29.37,4.79
17,CR00018,Social Media Marketing,Marketing,Free,Advanced,0.00,15.44,2.01
18,CR00019,Content Marketing,Marketing,Free,Advanced,0.00,18.00,2.98
19,CR00020,Email Marketing,Marketing,Free,Intermediate,0.00,46.25,4.11
20,CR00021,Data Analysis with Python,Data Science,Free,Intermediate,0.00,1.20,3.60
21,CR00022,Data Visualization,Data Science,Free,Beginner,0.00,32.64,3.65
22,CR00023,Machine Learning Fundamentals,Data Science,Free,Intermediate,0.00,9.71,3.02
23,CR00024,Big Data Analytics,Data Science,Paid,Advanced,117.68,48.09,2.57
24,CR00025,Statistical Analysis,Data Science,Paid,Beginner,299.57,48.32,3.74
25,CR00026,Intro to Machine Learning,Machine Learning,Free,Intermediate,0.00,47.70,4.73
26,CR00027,Neural Networks,Machine Learning,Free,Advanced,0.00,9.30,1.81
27,CR00028,Deep Learning,Machine Learning,Paid,Advanced,0.78,44.96,3.89
28,CR00029,Natural Language Processing,Machine Learning,Free,Beginner,0.00,16.33,1.13
29,CR00030,Reinforcement Learning,Machine Learning,Free,Intermediate,0.00,38.49,1.73
30,CR00031,Network Security,Cybersecurity,Free,Intermediate,0.00,26.52,1.91
31,CR00032,Ethical Hacking,Cybersecurity,Free,Advanced,0.00,16.74,2.38
32,CR00033,Cybersecurity Fundamentals,Cybersecurity,Free,Intermediate,0.00,48.25,3.93
33,CR00034,Data Encryption,Cybersecurity,Paid,Intermediate,394.26,47.44,1.35
34,CR00035,Cyber Threat Intelligence,Cybersecurity,Free,Beginner,0.00,42.59,4.94
35,CR00036,Agile Project Management,Project Management,Free,Beginner,0.00,15.75,4.68
36,CR00037,Scrum Essentials,Project Management,Free,Intermediate,0.00,33.93,3.45
37,CR00038,Risk Management,Project Management,Paid,Intermediate,342.61,17.14,4.84
38,CR00039,Project Planning,Project Management,Paid,Advanced,346.71,3.42,1.23
39,CR00040,Leadership in Projects,Project Management,Paid,Beginner,327.99,12.13,1.51
40,CR00041,Financial Accounting,Finance,Paid,Beginner,53.86,47.08,2.47
41,CR00042,Investment Strategies,Finance,Free,Intermediate,0.00,34.83,4.10
42,CR00043,Corporate Finance,Finance,Free,Beginner,0.00,31.77,4.14
43,CR00044,Personal Finance,Finance,Paid,Intermediate,119.04,23.41,2.75
44,CR00045,Financial Modeling,Finance,Free,Advanced,0.00,6.36,1.59
45,CR00046,AI for Beginners,Artificial Intelligence,Paid,Beginner,248.10,9.40,1.20
46,CR00047,Natural Language Processing,Artificial Intelligence,Paid,Intermediate,89.59,1.55,2.68
47,CR00048,AI Ethics,Artificial Intelligence,Free,Beginner,0.00,42.70,3.64
48,CR00049,Deep Learning,Artificial Intelligence,Paid,Intermediate,415.51,28.33,3.11
49,CR00050,Computer Vision,Artificial Intelligence,Paid,Beginner,490.90,7.55,4.55
50,CR00051,HTML & CSS,Web Development,Paid,Advanced,37.89,24.11,1.30
51,CR00052,JavaScript Mastery,Web Development,Free,Beginner,0.00,40.76,2.20
52,CR00053,React for Beginners,Web Development,Free,Advanced,0.00,40.07,2.67
53,CR00054,Backend Development with Node.js,Web Development,Free,Beginner,0.00,48.57,3.32
54,CR00055,Full-Stack Web Development,Web Development,Paid,Advanced,57.32,43.95,4.74
55,CR00056,Google Ads Mastery,Digital Marketing,Paid,Advanced,212.39,22.89,3.15
56,CR00057,SEO for E-commerce,Digital Marketing,Paid,Advanced,177.34,49.73,3.89
57,CR00058,Social Media Strategy,Digital Marketing,Free,Beginner,0.00,1.46,4.44
58,CR00059,Affiliate Marketing,Digital Marketing,Free,Intermediate,0.00,5.95,4.66
59,CR00060,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14

In [7]:
transactions

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID
0,TT00001,U00003,CR00016,25/10/2025,0.00,PayPal,TC00040
1,TT00002,U00003,CR00037,13/1/2025,0.00,PayPal,TC00040
2,TT00003,U00003,CR00019,28/3/2025,0.00,Bank Transfer,TC00040
3,TT00004,U00004,CR00048,2/6/2025,0.00,Bank Transfer,TC00040
4,TT00005,U00004,CR00060,10/8/2025,0.00,PayPal,TC00042
...,...,...,...,...,...,...,...
9995,TT09996,U02974,CR00045,1/12/2025,0.00,Credit Card,TC00040
9996,TT09997,U02976,CR00017,3/4/2025,0.00,PayPal,TC00040
9997,TT09998,U02980,CR00060,1/6/2025,0.00,PayPal,TC00040
9998,TT09999,U02981,CR00055,26/4/2025,57.32,Bank Transfer,TC00040
9999,TT10000,U02984,CR00043,18/10/2025,0.00,Credit Card,TC00042

In [8]:
teachers

,TeacherID,TeacherName,Age,Gender,Expertise,YearsOfExperience,TeacherRating
0,TC00001,Leonard Montgomery,44,Female,Cybersecurity,6,3.24
1,TC00002,Jill Day,32,Female,Digital Marketing,9,4.14
2,TC00003,Amber Torres,32,Male,Design,4,1.56
3,TC00004,Kristi Scott,34,Female,Machine Learning,9,4.39
4,TC00005,David Williams,34,Male,Finance,2,3.11
5,TC00006,Rebecca Webb,49,Male,Cybersecurity,14,3.36
6,TC00007,Angela Beard,28,Female,Machine Learning,6,4.36
7,TC00008,Steven Walker,41,Male,Data Science,15,3.54
8,TC00009,Alexander Tucker,49,Female,Project Management,2,2.22
9,TC00010,Frances Sanchez,29,Male,Data Science,1,2.18
10,TC00011,Carol Edwards,37,Female,Artificial Intelligence,8,3.55
11,TC00012,Christopher Nelson,48,Female,Cybersecurity,2,3.85
12,TC00013,Brian Carrillo,35,Female,Digital Marketing,6,3.42
13,TC00014,Susan Randolph,49,Male,Project Management,3,2.45
14,TC00015,John Armstrong,43,Male,Data Science,7,3.07
15,TC00016,David Carlson,33,Male,Data Science,1,2.92
16,TC00017,Brian Perez,36,Male,Digital Marketing,4,2.33
17,TC00018,Kari Pierce,47,Female,Project Management,11,4.28
18,TC00019,Tommy Haynes,35,Male,Digital Marketing,8,3.40
19,TC00020,Tara Reynolds,44,Female,Digital Marketing,10,3.23
20,TC00021,Adam Holmes,34,Female,Machine Learning,2,3.99
21,TC00022,John Holmes,33,Male,Digital Marketing,3,2.50
22,TC00023,Robert Mack,32,Male,Finance,4,2.99
23,TC00024,Michael Kim,40,Male,Digital Marketing,6,4.22
24,TC00025,Justin Pham,29,Male,Web Development,4,2.17
25,TC00026,Patrick Wilson,29,Male,Web Development,1,2.83
26,TC00027,Laurie Michael,44,Female,Artificial Intelligence,3,1.55
27,TC00028,Timothy Bailey,27,Female,Business,3,1.06
28,TC00029,David Webb,50,Male,Artificial Intelligence,2,3.10
29,TC00030,David Aguirre,50,Male,Artificial Intelligence,6,3.01
30,TC00031,Brenda Mercer,47,Female,Cybersecurity,1,1.86
31,TC00032,James Holder,44,Male,Cybersecurity,1,3.11
32,TC00033,Wesley Garcia,39,Female,Design,12,4.04
33,TC00034,Brandon Dawson,38,Male,Web Development,3,2.79
34,TC00035,Sharon Jackson,27,Male,Digital Marketing,5,3.13
35,TC00036,Brenda Mclean,28,Male,Digital Marketing,4,1.39
36,TC00037,Debra Escobar,47,Male,Finance,8,4.39
37,TC00038,Jeffrey Clark,43,Male,Digital Marketing,1,2.38
38,TC00039,Elizabeth Bishop,34,Male,Finance,7,3.31
39,TC00040,Kimberly Miller,49,Male,Cybersecurity,24,4.58
40,TC00041,Kevin Simpson,46,Male,Artificial Intelligence,7,3.55
41,TC00042,Yolanda Levine,49,Female,Machine Learning,21,4.97
42,TC00043,John Williams,30,Female,Project Management,1,1.05
43,TC00044,Barbara Maynard,27,Male,Finance,4,2.61
44,TC00045,Emily Gutierrez,28,Female,Web Development,5,1.07
45,TC00046,Brent Walters,33,Male,Cybersecurity,6,3.87
46,TC00047,Brad Griffin,27,Male,Design,4,1.79
47,TC00048,Theresa Gonzalez,30,Male,Finance,7,3.18
48,TC00049,Valerie Wiley,46,Female,Machine Learning,6,3.46
49,TC00050,Alexander Williams,32,Female,Digital Marketing,3,3.41
50,TC00051,John Obrien,36,Female,Design,2,1.77
51,TC00052,Susan Johnson,34,Female,Business,12,3.43
52,TC00053,Aaron Kirby,35,Male,Marketing,9,4.29
53,TC00054,Shelby Patrick,40,Female,Artificial Intelligence,7,4.28
54,TC00055,Alison Wilson,47,Female,Cybersecurity,12,3.53
55,TC00056,Alexis Everett,35,Female,Programming,9,3.95
56,TC00057,Brittany Scott,44,Male,Data Science,7,3.44
57,TC00058,Andrew Anderson,49,Male,Web Development,7,3.71
58,TC00059,Noah Stewart,48,Female,Cybersecurity,6,3.82
59,TC00060,Benjamin Gray,48,Female,Project Management,14,3.32

In [10]:
# Merge transactions with courses
data = transactions.merge(courses, on='CourseID', how='left')
data

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating
0,TT00001,U00003,CR00016,25/10/2025,0.00,PayPal,TC00040,Digital Marketing,Marketing,Free,Intermediate,0.00,42.68,4.72
1,TT00002,U00003,CR00037,13/1/2025,0.00,PayPal,TC00040,Scrum Essentials,Project Management,Free,Intermediate,0.00,33.93,3.45
2,TT00003,U00003,CR00019,28/3/2025,0.00,Bank Transfer,TC00040,Content Marketing,Marketing,Free,Advanced,0.00,18.00,2.98
3,TT00004,U00004,CR00048,2/6/2025,0.00,Bank Transfer,TC00040,AI Ethics,Artificial Intelligence,Free,Beginner,0.00,42.70,3.64
4,TT00005,U00004,CR00060,10/8/2025,0.00,PayPal,TC00042,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TT09996,U02974,CR00045,1/12/2025,0.00,Credit Card,TC00040,Financial Modeling,Finance,Free,Advanced,0.00,6.36,1.59
9996,TT09997,U02976,CR00017,3/4/2025,0.00,PayPal,TC00040,SEO Mastery,Marketing,Free,Advanced,0.00,29.37,4.79
9997,TT09998,U02980,CR00060,1/6/2025,0.00,PayPal,TC00040,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14
9998,TT09999,U02981,CR00055,26/4/2025,57.32,Bank Transfer,TC00040,Full-Stack Web Development,Web Development,Paid,Advanced,57.32,43.95,4.74
9999,TT10000,U02984,CR00043,18/10/2025,0.00,Credit Card,TC00042,Corporate Finance,Finance,Free,Beginner,0.00,31.77,4.14

In [11]:
# Merge with teachers (assuming TeacherID exists in courses)
data = data.merge(teachers, on='TeacherID', how='left')
data

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,TeacherName,Age,Gender,Expertise,YearsOfExperience,TeacherRating
0,TT00001,U00003,CR00016,25/10/2025,0.00,PayPal,TC00040,Digital Marketing,Marketing,Free,Intermediate,0.00,42.68,4.72,Kimberly Miller,49,Male,Cybersecurity,24,4.58
1,TT00002,U00003,CR00037,13/1/2025,0.00,PayPal,TC00040,Scrum Essentials,Project Management,Free,Intermediate,0.00,33.93,3.45,Kimberly Miller,49,Male,Cybersecurity,24,4.58
2,TT00003,U00003,CR00019,28/3/2025,0.00,Bank Transfer,TC00040,Content Marketing,Marketing,Free,Advanced,0.00,18.00,2.98,Kimberly Miller,49,Male,Cybersecurity,24,4.58
3,TT00004,U00004,CR00048,2/6/2025,0.00,Bank Transfer,TC00040,AI Ethics,Artificial Intelligence,Free,Beginner,0.00,42.70,3.64,Kimberly Miller,49,Male,Cybersecurity,24,4.58
4,TT00005,U00004,CR00060,10/8/2025,0.00,PayPal,TC00042,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14,Yolanda Levine,49,Female,Machine Learning,21,4.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,TT09996,U02974,CR00045,1/12/2025,0.00,Credit Card,TC00040,Financial Modeling,Finance,Free,Advanced,0.00,6.36,1.59,Kimberly Miller,49,Male,Cybersecurity,24,4.58
9996,TT09997,U02976,CR00017,3/4/2025,0.00,PayPal,TC00040,SEO Mastery,Marketing,Free,Advanced,0.00,29.37,4.79,Kimberly Miller,49,Male,Cybersecurity,24,4.58
9997,TT09998,U02980,CR00060,1/6/2025,0.00,PayPal,TC00040,Content Creation,Digital Marketing,Free,Beginner,0.00,8.95,2.14,Kimberly Miller,49,Male,Cybersecurity,24,4.58
9998,TT09999,U02981,CR00055,26/4/2025,57.32,Bank Transfer,TC00040,Full-Stack Web Development,Web Development,Paid,Advanced,57.32,43.95,4.74,Kimberly Miller,49,Male,Cybersecurity,24,4.58
9999,TT10000,U02984,CR00043,18/10/2025,0.00,Credit Card,TC00042,Corporate Finance,Finance,Free,Beginner,0.00,31.77,4.14,Yolanda Levine,49,Female,Machine Learning,21,4.97

In [12]:
data.head()

,TransactionID,UserID,CourseID,TransactionDate,Amount,PaymentMethod,TeacherID,CourseName,CourseCategory,CourseType,CourseLevel,CoursePrice,CourseDuration,CourseRating,TeacherName,Age,Gender,Expertise,YearsOfExperience,TeacherRating
0,TT00001,U00003,CR00016,25/10/2025,0.0,PayPal,TC00040,Digital Marketing,Marketing,Free,Intermediate,0.0,42.68,4.72,Kimberly Miller,49,Male,Cybersecurity,24,4.58
1,TT00002,U00003,CR00037,13/1/2025,0.0,PayPal,TC00040,Scrum Essentials,Project Management,Free,Intermediate,0.0,33.93,3.45,Kimberly Miller,49,Male,Cybersecurity,24,4.58
2,TT00003,U00003,CR00019,28/3/2025,0.0,Bank Transfer,TC00040,Content Marketing,Marketing,Free,Advanced,0.0,18.00,2.98,Kimberly Miller,49,Male,Cybersecurity,24,4.58
3,TT00004,U00004,CR00048,2/6/2025,0.0,Bank Transfer,TC00040,AI Ethics,Artificial Intelligence,Free,Beginner,0.0,42.70,3.64,Kimberly Miller,49,Male,Cybersecurity,24,4.58
4,TT00005,U00004,CR00060,10/8/2025,0.0,PayPal,TC00042,Content Creation,Digital Marketing,Free,Beginner,0.0,8.95,2.14,Yolanda Levine,49,Female,Machine Learning,21,4.97

### 2. Engagement Features

#### . Total Courses Entrolled

In [13]:
total_courses = data.groupby('UserID')['CourseID'].count().reset_index()
total_courses.rename(columns={'CourseID': 'total_courses'}, inplace=True)

In [14]:
total_courses

      UserID  total_courses
0     U00001              1
1     U00002              1
2     U00003             11
3     U00004             13
4     U00005              2
...      ...            ...
2995  U02996              1
2996  U02997              1
2997  U02998              1
2998  U02999              1
2999  U03000              1

[3000 rows x 2 columns]

#### . Enrollment Frequency

In [16]:
data['TransactionDate'] = pd.to_datetime(data['TransactionDate'])

enrollment_freq = data.groupby('UserID')['TransactionDate'].count().reset_index()
enrollment_freq.rename(columns={'TransactionDate': 'enrollment_frequency'}, inplace=True)

In [17]:
enrollment_freq

      UserID  enrollment_frequency
0     U00001                     1
1     U00002                     1
2     U00003                    11
3     U00004                    13
4     U00005                     2
...      ...                   ...
2995  U02996                     1
2996  U02997                     1
2997  U02998                     1
2998  U02999                     1
2999  U03000                     1

[3000 rows x 2 columns]

#### . Courses per Category

In [18]:
courses_per_category = data.groupby(['UserID', 'CourseCategory']).size().unstack(fill_value=0)
courses_per_category.reset_index(inplace=True)

In [19]:
courses_per_category

CourseCategory,UserID,Artificial Intelligence,Business,Cybersecurity,Data Science,Design,Digital Marketing,Finance,Machine Learning,Marketing,Programming,Project Management,Web Development
0,U00001,0,0,1,0,0,0,0,0,0,0,0,0
1,U00002,0,0,0,0,0,0,0,0,0,1,0,0
2,U00003,1,0,0,0,0,1,1,0,4,1,2,1
3,U00004,2,0,0,2,0,3,1,1,2,0,1,1
4,U00005,0,0,0,0,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,U02996,0,0,0,0,0,0,1,0,0,0,0,0
2996,U02997,0,0,0,0,0,0,0,1,0,0,0,0
2997,U02998,0,0,0,0,0,0,0,0,0,0,0,1
2998,U02999,0,0,0,0,0,0,0,0,0,0,0,1
2999,U03000,0,0,1,0,0,0,0,0,0,0,0,0

### 3. Preference Features

#### . Preferred Category

In [20]:
pref_category = data.groupby(['UserID', 'CourseCategory']).size().reset_index(name='count')

pref_category = pref_category.sort_values(['UserID', 'count'], ascending=False)
pref_category = pref_category.drop_duplicates('UserID')

pref_category = pref_category[['UserID', 'CourseCategory']]
pref_category.rename(columns={'CourseCategory': 'preferred_category'}, inplace=True)

In [21]:
pref_category

      UserID preferred_category
7731  U03000      Cybersecurity
7730  U02999    Web Development
7729  U02998    Web Development
7728  U02997   Machine Learning
7727  U02996            Finance
...      ...                ...
17    U00005        Programming
11    U00004  Digital Marketing
5     U00003          Marketing
1     U00002        Programming
0     U00001      Cybersecurity

[3000 rows x 2 columns]

#### . Preferred Course level

In [27]:
pref_level = data.groupby(['UserID', 'CourseLevel']).size().reset_index(name='count')

pref_level = pref_level.sort_values(['UserID', 'count'], ascending=False)
pref_level = pref_level.drop_duplicates('UserID')

pref_level = pref_level[['UserID', 'CourseLevel']]
pref_level.rename(columns={'CourseLevel': 'preferred_level'}, inplace=True)

In [23]:
pref_level

      UserID preferred_level
4667  U03000    Intermediate
4666  U02999        Advanced
4665  U02998        Advanced
4664  U02997        Advanced
4663  U02996        Beginner
...      ...             ...
8     U00005        Advanced
7     U00004    Intermediate
2     U00003        Advanced
1     U00002        Beginner
0     U00001    Intermediate

[3000 rows x 2 columns]

#### . Average Course Rating

In [24]:
avg_rating = data.groupby('UserID')['CourseRating'].mean().reset_index()
avg_rating.rename(columns={'CourseRating': 'avg_course_rating'}, inplace=True)

In [25]:
avg_rating

      UserID  avg_course_rating
0     U00001           1.350000
1     U00002           2.880000
2     U00003           2.889091
3     U00004           3.451538
4     U00005           2.055000
...      ...                ...
2995  U02996           4.140000
2996  U02997           1.810000
2997  U02998           1.300000
2998  U02999           1.300000
2999  U03000           1.350000

[3000 rows x 2 columns]

### 4. Behavioral Features

#### . Average Spending

In [28]:
avg_spending = data.groupby('UserID')['Amount'].mean().reset_index()
avg_spending.rename(columns={'Amount': 'avg_spending'}, inplace=True)

In [29]:
avg_spending

      UserID  avg_spending
0     U00001    394.260000
1     U00002      0.000000
2     U00003     55.816364
3     U00004     75.542308
4     U00005    173.355000
...      ...           ...
2995  U02996      0.000000
2996  U02997      0.000000
2997  U02998     37.890000
2998  U02999     37.890000
2999  U03000    394.260000

[3000 rows x 2 columns]

#### . Total Spending

In [30]:
total_spending = data.groupby('UserID')['Amount'].sum().reset_index()
total_spending.rename(columns={'Amount': 'total_spending'}, inplace=True)

In [31]:
total_spending

      UserID  total_spending
0     U00001          394.26
1     U00002            0.00
2     U00003          613.98
3     U00004          982.05
4     U00005          346.71
...      ...             ...
2995  U02996            0.00
2996  U02997            0.00
2997  U02998           37.89
2998  U02999           37.89
2999  U03000          394.26

[3000 rows x 2 columns]

#### . Diversity Score (Categories Explored)

In [32]:
diversity = data.groupby('UserID')['CourseCategory'].nunique().reset_index()
diversity.rename(columns={'CourseCategory': 'diversity_score'}, inplace=True)

In [33]:
diversity

      UserID  diversity_score
0     U00001                1
1     U00002                1
2     U00003                7
3     U00004                8
4     U00005                2
...      ...              ...
2995  U02996                1
2996  U02997                1
2997  U02998                1
2998  U02999                1
2999  U03000                1

[3000 rows x 2 columns]

#### . Learning Depth Index (Beginner vs Advanced)

In [34]:
level_counts = data.groupby(['UserID', 'CourseLevel']).size().unstack(fill_value=0)

# Avoid error if columns missing
if 'Beginner' not in level_counts:
    level_counts['Beginner'] = 0
if 'Advanced' not in level_counts:
    level_counts['Advanced'] = 0

level_counts['learning_depth_index'] = level_counts['Advanced'] / (level_counts['Beginner'] + 1)

level_counts = level_counts[['learning_depth_index']].reset_index()

In [35]:
level_counts

CourseLevel  UserID  learning_depth_index
0            U00001                   0.0
1            U00002                   0.0
2            U00003                   0.8
3            U00004                   0.6
4            U00005                   0.5
...             ...                   ...
2995         U02996                   0.0
2996         U02997                   1.0
2997         U02998                   1.0
2998         U02999                   1.0
2999         U03000                   0.0

[3000 rows x 2 columns]

### 5. Teacher-Based Features

#### . Preferred Teacher

In [36]:
pref_teacher = data.groupby(['UserID', 'TeacherID']).size().reset_index(name='count')

pref_teacher = pref_teacher.sort_values(['UserID', 'count'], ascending=False)
pref_teacher = pref_teacher.drop_duplicates('UserID')

pref_teacher = pref_teacher[['UserID', 'TeacherID']]
pref_teacher.rename(columns={'TeacherID': 'preferred_teacher'}, inplace=True)

In [37]:
pref_teacher

      UserID preferred_teacher
4700  U03000           TC00001
4699  U02999           TC00026
4698  U02998           TC00034
4697  U02997           TC00017
4696  U02996           TC00048
...      ...               ...
6     U00005           TC00015
4     U00004           TC00040
2     U00003           TC00040
1     U00002           TC00009
0     U00001           TC00031

[3000 rows x 2 columns]

#### . Teacher Diversity

In [38]:
teacher_diversity = data.groupby('UserID')['TeacherID'].nunique().reset_index()
teacher_diversity.rename(columns={'TeacherID': 'teacher_diversity'}, inplace=True)

In [39]:
teacher_diversity

      UserID  teacher_diversity
0     U00001                  1
1     U00002                  1
2     U00003                  2
3     U00004                  2
4     U00005                  2
...      ...                ...
2995  U02996                  1
2996  U02997                  1
2997  U02998                  1
2998  U02999                  1
2999  U03000                  1

[3000 rows x 2 columns]

### 6. Final Learner Profile

In [40]:
learner_profile = users.copy()

dfs = [
    total_courses,
    enrollment_freq,
    avg_spending,
    total_spending,
    diversity,
    avg_rating,
    pref_category,
    pref_level,
    level_counts,
    pref_teacher,
    teacher_diversity
]

for df in dfs:
    learner_profile = learner_profile.merge(df, on='UserID', how='left')

# Fill missing values
learner_profile.fillna(0, inplace=True)

learner_profile.head()

,UserID,UserName,Age,Gender,Email,total_courses,enrollment_frequency,avg_spending,total_spending,diversity_score,avg_course_rating,preferred_category,preferred_level,learning_depth_index,preferred_teacher,teacher_diversity
0,U00001,wilsonjordan,15,Male,patricia27@hotmail.com,1,1,394.260000,394.26,1,1.350000,Cybersecurity,Intermediate,0.0,TC00031,1
1,U00002,angela22,29,Female,hallrandy@hotmail.com,1,1,0.000000,0.00,1,2.880000,Programming,Beginner,0.0,TC00009,1
2,U00003,morrisonamanda,33,Female,ganderson@yahoo.com,11,11,55.816364,613.98,7,2.889091,Marketing,Advanced,0.8,TC00040,2
3,U00004,fthornton,23,Female,christensencatherine@outlook.com,13,13,75.542308,982.05,8,3.451538,Digital Marketing,Intermediate,0.6,TC00040,2
4,U00005,fostergeoffrey,21,Male,karenfuentes@yahoo.com,2,2,173.355000,346.71,2,2.055000,Programming,Advanced,0.5,TC00015,2

### 7. Save Final Dataset

In [41]:
learner_profile.to_csv("../outputs/learner_profile.csv", index=False)